/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EbayCallbackRouteImport } from './routes/ebay.callback'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRulesRouteImport } from './routes/_authenticated/rules'
import { Route as AuthenticatedOptimizerRouteImport } from './routes/_authenticated/optimizer'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedListingsRouteImport } from './routes/_authenticated/listings'
import { Route as AuthenticatedDraftsRouteImport } from './routes/_authenticated/drafts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as AuthenticatedProductsPidRouteImport } from './routes/_authenticated/products.$pid'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EbayCallbackRoute = EbayCallbackRouteImport.update({
  id: '/ebay/callback',
  path: '/ebay/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRulesRoute = AuthenticatedRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOptimizerRoute = AuthenticatedOptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListingsRoute = AuthenticatedListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDraftsRoute = AuthenticatedDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsPidRoute =
  AuthenticatedProductsPidRouteImport.update({
    id: '/products/$pid',
    path: '/products/$pid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/optimizer': typeof AuthenticatedOptimizerRoute
  '/rules': typeof AuthenticatedRulesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/ebay/callback': typeof EbayCallbackRoute
  '/products/$pid': typeof AuthenticatedProductsPidRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/optimizer': typeof AuthenticatedOptimizerRoute
  '/rules': typeof AuthenticatedRulesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/ebay/callback': typeof EbayCallbackRoute
  '/products/$pid': typeof AuthenticatedProductsPidRoute
  '/products': typeof AuthenticatedProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/drafts': typeof AuthenticatedDraftsRoute
  '/_authenticated/listings': typeof AuthenticatedListingsRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/optimizer': typeof AuthenticatedOptimizerRoute
  '/_authenticated/rules': typeof AuthenticatedRulesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/ebay/callback': typeof EbayCallbackRoute
  '/_authenticated/products/$pid': typeof AuthenticatedProductsPidRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/drafts'
    | '/listings'
    | '/logs'
    | '/optimizer'
    | '/rules'
    | '/settings'
    | '/ebay/callback'
    | '/products/$pid'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/drafts'
    | '/listings'
    | '/logs'
    | '/optimizer'
    | '/rules'
    | '/settings'
    | '/ebay/callback'
    | '/products/$pid'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/drafts'
    | '/_authenticated/listings'
    | '/_authenticated/logs'
    | '/_authenticated/optimizer'
    | '/_authenticated/rules'
    | '/_authenticated/settings'
    | '/ebay/callback'
    | '/_authenticated/products/$pid'
    | '/_authenticated/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EbayCallbackRoute: typeof EbayCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebay/callback': {
      id: '/ebay/callback'
      path: '/ebay/callback'
      fullPath: '/ebay/callback'
      preLoaderRoute: typeof EbayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rules': {
      id: '/_authenticated/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AuthenticatedRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/optimizer': {
      id: '/_authenticated/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof AuthenticatedOptimizerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings': {
      id: '/_authenticated/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof AuthenticatedListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drafts': {
      id: '/_authenticated/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof AuthenticatedDraftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/$pid': {
      id: '/_authenticated/products/$pid'
      path: '/products/$pid'
      fullPath: '/products/$pid'
      preLoaderRoute: typeof AuthenticatedProductsPidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDraftsRoute: typeof AuthenticatedDraftsRoute
  AuthenticatedListingsRoute: typeof AuthenticatedListingsRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedOptimizerRoute: typeof AuthenticatedOptimizerRoute
  AuthenticatedRulesRoute: typeof AuthenticatedRulesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProductsPidRoute: typeof AuthenticatedProductsPidRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDraftsRoute: AuthenticatedDraftsRoute,
  AuthenticatedListingsRoute: AuthenticatedListingsRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedOptimizerRoute: AuthenticatedOptimizerRoute,
  AuthenticatedRulesRoute: AuthenticatedRulesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProductsPidRoute: AuthenticatedProductsPidRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EbayCallbackRoute: EbayCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
